# Generated by Django 5.2 on 2025-04-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AddField(
            model_name='client',
            name='encrypted_email',
            field=models.BinaryField(null=True),
        ),
    ]
