# Generated by Django 5.2 on 2025-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_client_email_client_encrypted_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='encrypted_email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
