name: test db connect 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123654789
          POSTGRES_DB: Auto_Service
        ports:
          - 5432:5432  
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Apply migrations
        working-directory: ./AutoServis
        run: python manage.py migrate

      - name: Run unittests
        working-directory: ./AutoServis 
        run: python manage.py test

      - name: Run pytests
        working-directory: ./AutoServis
        run: pytest -v